module.exports = {
    LOAD_TASK_DATA: 'LOAD_TASK_DATA',
    SET_BOARD_DATA: 'SET_BOARD_DATA',
    SET_CARD_DATA: 'SET_CARD_DATA',
    SET_LIST_OF_LISTS: 'SET_LIST_OF_LISTS',
    DELETE_LIST_FROM_BOARD: 'DELETE_LIST_FROM_BOARD',
    SET_NEW_CARD: 'SET_NEW_CARD',
    DELETE_CARD_FROM_LIST: 'DELETE_CARD_FROM_LIST'

}